name: 'Linux Setup'
description: 'Setup common dependencies and environment for CI'
inputs:
  compiler:
    description: 'Compiler to use'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.30.x'

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: |
            ${{ env.VCPKG_INSTALLATION_ROOT }}
            ~/.cache/vcpkg/archives
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
            vcpkg-${{ runner.os }}-

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: "Set environmental variables"
      shell: bash
      run: |
        echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

    - name: Install nasm and other libraries on Linux
      shell: bash
      run: sudo apt-get install -y nasm
